# Generated by Django 4.1.7 on 2023-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mental_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
