# Generated by Django 4.1.7 on 2023-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_option',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
