# Generated by Django 4.1.7 on 2023-03-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='selected_option',
        ),
    ]
