# Generated by Django 4.1.7 on 2023-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_question_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_option',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
