# Generated by Django 4.1.7 on 2023-03-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_question_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='selected_option',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
